### ISSUE TITLE
can't download data

### ISSUE THREAD

**Issue by helloword12345678** [kedz/summarization-datasets#1]
hi:
the  CNN/DailyMail Dataset  can not download,
https://docs.google.com/uc?export=download?id=0BzQ6rtO2VN95bndCZDdpdXJDV1U

**Comment by kedz** [comment]
Just checked out the code and tried it and it worked for me. Can you give me an error message?
Also can you verify that you can download the links for CNN_STORIES_TOKENIZED and DM_STORIES_TOKENIZED from this page: https://github.com/JafferWilson/Process-Data-of-CNN-DailyMail

**Comment by helloword12345678** [comment]
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='docs.google.com', port=443): Max retries exceeded with url: /uc?export=download&id=0BzQ6rtO2VN95bndCZDdpdXJDV1U (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x1061ed3c8>: Failed to establish a new connection: [Errno 60] Operation timed out',))

**Comment by helloword12345678** [comment]
solved, i download it by hand not in program

**Comment by yomnashaban** [comment]
hello, can you guide me through how to install rouge_papier?
